version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=recruitment
      - DB_PASS=recruitment
    ports:
      - "8000:8000"
  db:
    image: postgres
    environment:
      - POSTGRES_DB=recruitment
      - POSTGRES_USER=recruitment
      - POSTGRES_PASSWORD=recruitment
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
