# Generated by Django 4.2.5 on 2023-09-14 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="uuid",
            new_name="uid",
        ),
    ]
