# Generated by Django 4.2.5 on 2023-09-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="displayed_picture",
            field=models.BooleanField(default=False),
        ),
    ]
